// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvcaT9eRK3xUDCCS9IM9gOMmLef_96Wg',
    appId: '1:864344637924:web:62da38c042c8b4f798c7f1',
    messagingSenderId: '864344637924',
    projectId: 'reservations-app-6eae1',
    authDomain: 'reservations-app-6eae1.firebaseapp.com',
    storageBucket: 'reservations-app-6eae1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPfjJgakhe0EMLjzZNMkLnxoN06izxOwo',
    appId: '1:864344637924:android:ffa2d59639e08d1698c7f1',
    messagingSenderId: '864344637924',
    projectId: 'reservations-app-6eae1',
    storageBucket: 'reservations-app-6eae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBy_OZL0drJ2-r4zh6EGB70mxw0zh1ZNo',
    appId: '1:864344637924:ios:6a2e72d23129f1f898c7f1',
    messagingSenderId: '864344637924',
    projectId: 'reservations-app-6eae1',
    storageBucket: 'reservations-app-6eae1.firebasestorage.app',
    iosBundleId: 'com.example.reservationsApp',
  );
}
